version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: icatto_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: icatto
      POSTGRES_PASSWORD: icatto_dev
      POSTGRES_DB: icatto_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
